#Timeout (in seconds) that Limine will use before automatically booting
timeout: 5

# Entry name that will apppear in boot menu
/myOS
  protocol: limine
  #Path to kernel to boot. Boot():/ represents partition on which limine.conf is located
  path: boot():/boot/myos
